### ISSUE TITLE
Escualo should restart services if they get unresponsive though http

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-escualo#8]

**Comment by faloi** [comment]
I think we should use [monit](https://mmonit.com/monit/) for this, I did some research and it's the most lightweight utility and yet very easy to configure in a nice declarative way:

```
check host mmonit.com with address mmonit.com
       if failed port 80 protocol http then alert
```

**Comment by flbulgarelli** [comment]
:+1:
